### ISSUE TITLE
slf4j MDCAdapter with multi-thread-context 支持

### ISSUE THREAD

**Issue by bwzhang2011** [alibaba/multi-thread-context#51]
@oldratlee, 能否进一步提供`multi-thread-context`针对`slf4j MDCAdapter`的集成支持。`MDCAdapter`是`slf4j spi`的定义， `logback`以及`log4j2`等均提供了实现。

但个人感觉里面的跨线程上下文传递应该没有`multi-thread-context`考虑得那么完备（也能否帮忙看一下`LOG4J2`内部的实现能否满足`multi-thread-context`实现的那样），鉴于日志场景中许多事基于`slf4j`的（不想`MDC`的地方调用了一次，然后又调用一次`multi-thread-context`中`threadLocal`方式），看能否提供一个这样的替代实现（或者通过`java instrument api`替代掉原有的`MDCAdapter`实现--可由`multi-thread-context`实现）。这个实现能缺省提供则有保障（个人只是有这个思路）

**Comment by bwzhang2011** [comment]
@oldratlee，是否考虑对multi-thread-context的一些使用增强一下。类似于sl4j的MDC类，大部分类似于MAP的操作，不需要关心threadLocal的操作(如创建、初始化等，这个操作由MdcAdapter来完成)。

**Comment by oldratlee** [comment]
你说的`sl4j`是指[`slf4j`](http://www.slf4j.org/) 是吧？

 > 鉴于日志场景中许多事基于`sl4j`的（不想`MDC`的地方调用了一次，然后又调用一次`multi-thread-context`中`threadLocal`方式），看能否提供一个这样的替代实现（或者通过`java instrument api`替代掉原有的`MDCAdapter`实现--可由`multi-thread-context`实现）

从『`MDC`的地方调用了一次，然后又调用一次`multi-thread-context`中`threadLocal`』的方式 到 提供 `MDCAdapter SPI`的实现，是把前一种方式中『两次设置』的逻辑 在`MDCAdapter SPI`中实现。

提供一个`MDCAdapter SPI`实现。

思路OK的。

你了解一下如何开发`MDCAdapter SPI`，然后给个实现一个不？求贡献代码，如何？ :smile_cat: 

PS： 最近比较没有没有时间去看 `MDCAdapter SPI`的用法。

**Comment by bwzhang2011** [comment]
@oldratlee, sorry，那是笔误。就使用而言，
//省略
ThreadContext.put(TRACE_ID, TRACE_ID_VALUE);
 mtc.get().put(TRACE_ID, TRACE_ID_VALUE);

上述需要你写两步，一步是调用ThreadContext下一步是使用mtc，但都是同样上下文变量的处理。所以这样的集成实际价值不大（也就是要么以MDC的处理方式为主，要么以MTC为主）

MDC中也集成了threadlocal的使用，但不清楚是否达到了MTC的效果。MTC对于跨现场的处理中有restore这样的方式（但貌似MDC的实现，即MDCAdapter关联的部分又没有，就不确定是否能达到等同的传递线程变量的效果了）

**Comment by oldratlee** [comment]
> MDC中也集成了threadlocal的使用，但不清楚是否达到了MTC的效果

`ThreadLocal`不能解决到Thread Pool线程的Context，MTC解决这个问题，本身就是继承`ThreadLocal`实现的。

另外，看了一下，`slf4j`的[`MDC`实现类](http://grepcode.com/file_/repo1.maven.org/maven2/org.slf4j/slf4j-api/1.7.12/org/slf4j/MDC.java/?v=source)：

```java
  static {
    try {
      mdcAdapter = StaticMDCBinder.SINGLETON.getMDCA();
    } catch (NoClassDefFoundError ncde) {
      mdcAdapter = new NOPMDCAdapter();
      String msg = ncde.getMessage();
      if (msg != null && msg.indexOf("StaticMDCBinder") != -1) {
        Util.report("Failed to load class \"org.slf4j.impl.StaticMDCBinder\".");
        Util.report("Defaulting to no-operation MDCAdapter implementation.");
        Util
            .report("See " + NO_STATIC_MDC_BINDER_URL + " for further details.");
      } else {
        throw ncde;
      }
    } catch (Exception e) {
      // we should never get here
      Util.report("MDC binding unsuccessful.", e);
    }
  }
```

`slf4j`加载具体实现`StaticMDCBinder`类，是通过静态类名加载的，如 `Log4j`提供的`StaticMDCBinder`类如下：

```java
public class StaticMDCBinder {

  
  /**
   * The unique instance of this class.
   */
  public static final StaticMDCBinder SINGLETON = new StaticMDCBinder();

  private StaticMDCBinder() {
  }
  
  /**
   * Currently this method always returns an instance of 
   * {@link StaticMDCBinder}.
   */
  public MDCAdapter getMDCA() {
     return new Log4jMDCAdapter();
  }
  
  public String  getMDCAdapterClassStr() {
    return Log4jMDCAdapter.class.getName();
  }
}
```

写了要加载的`Log4jMDCAdapter`类，所以不能换`Log4jMDCAdapter`的实现。

**Comment by oldratlee** [comment]
> 写了要加载的Log4jMDCAdapter类，所以 不能换Log4jMDCAdapter的实现，以加上MTC相关的逻辑。目前的slf4j的MDC设计是如此。

要加强`slf4j`的设计，以支持 自动定义`MDCAdapter`，这个估计，比较慢，并且需要和`slf4j`的同学聊。

如果跨`ThreadPool`线程传递LogContext，你现在有需要，推荐先按之前 可以Run方案做了，后面再跟进`slf4j`的问题吧。

**Comment by bwzhang2011** [comment]
@oldratlee, 的确。对了，鼎哥能否确定一个时期。就是log4j2的threadContext也有类似的提示：
However, as discussed in the Executors class and in other cases where thread pooling is utilized, the ThreadContext may not always be automatically passed to worker threads. In those cases the pooling mechanism should provide a means for doing so. The getContext() and cloneStack() methods can be used to obtain copies of the Map and Stack respectively.

它上面有一段有暗示但没有提示的话：
 In those cases the pooling mechanism should provide a means for doing so.
但是没有说明the pooling merchanisom提供何种手段。

那就等好消息了，我后续花一些时间按照Run的方式来写。日志还是沿用MDC.put但提取数据则是从mtc中提取，这样是否可行。

**Comment by bwzhang2011** [comment]
@oldratlee, 我使用log4j2对应的MDCAdapter实现。感觉跨线程（包括executorService）也是可以的，但不清楚什么时候是无效的，譬如上述文档中的may not be always be passed to worker thread. 作为建议还是希望工程自身提供一个近似MDC的帮助类，这样我可以不去管mtc的创建，只需要与其进行操作即可。

**Comment by oldratlee** [comment]
> 鼎哥能否确定一个事情：就是log4j2的threadContext也有类似的提示 ...

> 我使用log4j2对应的MDCAdapter实现。感觉跨线程（包括executorService）也是可以的，但不清楚什么时候是无效的，譬如上述文档中的may not be always be passed to worker thread.

无效时候，应该就是`MTC`要解决的问题对应的情况。 

PS： 这是不停地给我派活啊。。。

**Comment by bwzhang2011** [comment]
@oldratlee，这不是我的本意啊，不过你也是大牛了。俗话说得好送佛送到西，我刚才表述的想必你也能理解了。如果能进一步的话，至少 MTC可以作为MTC的非官方的缺省实现，既可以满足日志需求也可以满足上下文传递所需要的其他场景。之所以要用MDC的日志，是因为我们的平台有做日志归集的需求，需要通过类似syslog appender这样的流将本地的日志上传到远端比如FLUME。而改动应用最小的又能现有结合比较好的就只有日志LOGGER（而slf4j则当前用得比较广泛）。以MDC来比较MTC的一些测试类，当然MDC更直观（里面是一些静态方法，直接操作就OK了），想必这也是MTC可以进一步可便利化的地方，拜托了。

**Comment by oldratlee** [comment]
客气了~

目前`slf4j`目前不能指定`MDCAdapter`的实现，一个做法把`slf4j-impl`中的`MDCAdapter`实现改了，加上`multi-thread-context`的逻辑。

这样的解法，使用者需要使用改写了的`slf4j-impl`。

另外，从你的说明来看，传递`multi-thread-context`对应用代码是透明的（不期望应用代码使用`MtContextRunnable`或是`MtContextCallable`），在Java的启动参数加上：

- `-Xbootclasspath/a:/path/to/multithread.context-1.1.0.jar`
- `-javaagent:/path/to/multithread.context-1.1.0.jar`

**Comment by oldratlee** [comment]
slf4j-log4j12实现中的MDCAdapter实现修改了，支持`MTC` https://github.com/oldratlee/log4j-slf4j-impl-patch-mtc  @bwzhang2011

**Comment by bwzhang2011** [comment]
@oldratlee, 非常感谢持续的改进和推动。如有问题或其他建议，再在那个patch上跟进和沟通。

**Comment by oldratlee** [comment]
@bwzhang2011 用起来了？可以反馈一下问题解决的如何 :)

**Comment by bwzhang2011** [comment]
@oldratlee, 可以用起来。感觉跟直接用MDC差不不大，能否直接替代掉ThreadContext中的ThreadContextMap的实现。

**Comment by oldratlee** [comment]
整个过程用起来还是有些麻烦，给力！:+1:  

> 直接替代掉...的实现

给给一下期望使用方式的代码吗？方便我感觉一下 :smile:

**Comment by bwzhang2011** [comment]
@oldratlee, 抱歉昨天忘记看回复了。是的，诚如你说的。如果能在实现中替代掉应该是比较直接的方式，可否增加mtc-extension的工程，如果可如此替代的话。以log4j2中依赖https://github.com/apache/logging-log4j2/blob/master/log4j-api/src/main/java/org/apache/logging/log4j/spi/DefaultThreadContextMap.java，可否通过agent方式替代掉这个。

**Comment by bwzhang2011** [comment]
@oldratlee, 不知道上述想法是否可行，还是会存在问题。如果adapter中实现的部分均是靠threadContextMap的threadLocal关联的map来操作，若替代成MTC的threadlocal是否能解决问题。可避免新的工程，不知是否可行。

**Comment by bwzhang2011** [comment]
@oldratlee, 我再仔细REVIEW了LOG4J2中的ThreaContext代码。其中初始化的部分：
final String threadContextMapName = managerProps.getStringProperty(THREAD_CONTEXT_KEY);
        final ClassLoader cl = ProviderUtil.findClassLoader();
        if (threadContextMapName != null) {
            try {
                final Class<?> clazz = cl.loadClass(threadContextMapName);
                if (ThreadContextMap.class.isAssignableFrom(clazz)) {
                    contextMap = (ThreadContextMap) clazz.newInstance();
                }
            } catch (final ClassNotFoundException cnfe) {
                LOGGER.error("Unable to locate configured ThreadContextMap {}", threadContextMapName);
            } catch (final Exception ex) {
                LOGGER.error("Unable to create configured ThreadContextMap {}", threadContextMapName, ex);
            }
        }

也就是可以设置一个机遇MTC的ThreadContextMap实现即可——由应用来决定是否（只是面向LOG4J2的）。现在我遇到一个问题就是初始化的部分，即LOG4J2的缺省实现为：
new InheritableThreadLocal<Map<String, String>>() {
                @Override
                protected Map<String, String> childValue(final Map<String, String> parentValue) {
                    return parentValue != null && isMapEnabled //
                            ? Collections.unmodifiableMap(new HashMap<String, String>(parentValue)) //
                            : null;
                }
            };

上述是在childValue中构建一个map。但看过你在patch工程部分中的Log4jMDCAdapter的部分
 MtContextThreadLocal<Map<String, String>> log4j2Context = new MtContextThreadLocal<Map<String, String>>() {
        @Override
        protected void beforeExecute() {
            final Map<String, String> log4j2Context = get();
            for (Map.Entry<String, String> entry : log4j2Context.entrySet()) {
                ThreadContext.put(entry.getKey(), entry.getValue());
            }
        }

        @Override
        protected void afterExecute() {
            ThreadContext.clearAll();
        }

        @Override
        protected Map<String, String> initialValue() {
            return new HashMap<String, String>();
        }
    };

貌似没有去覆盖childValue的部分。我想确认的是如果重新构建一个基于MTC的localMap初始化的部分该如何编写。

**Comment by bwzhang2011** [comment]
@oldratlee，我到那个patch上提一个issue了。看能否提供一个你的官方实现。

**Comment by oldratlee** [comment]
> 将`THREAD_CONTEXT_KEY`的路径指向你自己实现的`threadContextMap`即可，这样就做到了拔插。

按你的这个方案，实现了 https://github.com/oldratlee/log4j2-mtc-thread-context-map

把这个依赖放到项目中，即开启 `Log4j2`用`MtcThreadContextMap`。
