### ISSUE TITLE
分布式追踪系统场景下，如何使用MTC

### ISSUE THREAD

**Issue by wyzssw** [alibaba/multi-thread-context#53]
子线程无法修改父线程 threadlocal，不知道设计时是否支持该功能

```java
ExecutorService service = Executors.newFixedThreadPool(1);
    
    ExecutorService executorService =  MtContextExecutors.getMtcExecutorService(service); 

     final MtContextThreadLocal<String> parent = new MtContextThreadLocal<String>();
     parent.set("value-set-in-parent");

     executorService.submit(new Runnable() {
      
      @Override
      public void run() {
        System.out.println(parent.get());
        parent.set("asf");
      }
    });
    
     Thread.sleep(1000);
     String value = parent.get(); 
     System.out.println(value);
```

打印出

```
value-set-in-parent
value-set-in-parent
```

**Comment by oldratlee** [comment]
你好，MTC 本身是 `ThreadLocal`（继承关系），不同的线程各自有一份，即是独立的。

和`ThreadLocal`一样，往往是`static`，全局一份，通过`MtContextThreadLocal`变量查看/修改的自己线程的哪个拷贝。

```java
ExecutorService service = Executors.newFixedThreadPool(1);
ExecutorService executorService =  MtContextExecutors.getMtcExecutorService(service); 

// 通过`MtContextThreadLocal`变量查看/修改的自己线程的哪个拷贝
// 所以命名 不用Parent，往往按用途命名
static final MtContextThreadLocal<String> storeTestContext = new MtContextThreadLocal<String>();

// Use

public void testMethod() {
    parent.set("value-set-in-parent");

     executorService.submit(new Runnable() {
      @Override
      public void run() {
        System.out.println(parent.get());
        parent.set("asf");
      }
    });

     Thread.sleep(1000);
     String value = parent.get(); 
     System.out.println(value);
}
```

**Comment by oldratlee** [comment]
可以先说说你的需求/要解决的问题。再看看合适的解决方案。

**Comment by wyzssw** [comment]
我现在做一套分布式追踪系统，比如一次rpc调用，client-A调用server-B，server-B要多线程并行调用server-C和server-D获取结果，server-B聚合结果返回给client-A。
框架里面要对这次调用链记录traceId和spanId(类似淘宝鹰眼的rpcId),在上述例子中，client-A 到 server-B的调用标识(spanId)为1,server-B 到server-C的调用标识(spanId)为1.1，server-B到server-D的调用标识(spanId)为1.2。
      在同一trace调用链中，每个spanId是唯一的，server-B将接收到由client-A生成的spanId放到MtContextThreadLocal<String>变量名 spanIdLocal，还有一个变量MtContextThreadLocal<AtmicLong> 作为计数器,变量名autoIncrLocal。
     子线程 生成spanId时，使用String spanId=spanIdLocal.get()+"."+autoIncrLocal.get().incrementAndGet()
     父线程通过future.get()获取server-B和server-C的结果后，将autoIncrLocal清零--autoIncrLocal.get().set(0)以供下次rpc调用链使用。

因为MtContextThreadLocal无法满足我的需求，我现在换成ConcurrentMap<Long, AtomicLong> autoIncr = new ConcurrentHashMap<>(100); key是traceId，value是计数器，来做的。

**Comment by oldratlee** [comment]
明白你的场景了，分布式追踪系统是个赞组件 :+1: 

把你说的Server调用，展开画个示意图：

```
Client A  +---> Server B(1) +---> Server C(1.1)
          |                 |
          |                 \---> Server D(1.2)
          |
          \---> Server E(2) +---> Server F(2.1)
                            |
                            \---> Server G(2.2)
```

**Comment by wyzssw** [comment]
多谢回复

是的，和你的思路是一样的，traceId 的多线程传递我用的就是MTC，唯一一点侵入就是需要业务代码中使用MtContextExecutors修饰下线程池。

**Comment by oldratlee** [comment]
关于『用全局的ConcurrentMap实现 TraceId对应的 当前Server一级的SpanId的使用记录』，调用完成时，需要清除Map中的 TraceId 的条目，避免内存泄漏，TraceId随着时间推移会有很多。

你是如何做的？

**Comment by wyzssw** [comment]
你到提醒了我，我之前没有考虑oneway方法的rpc请求，只考虑了父线程会等到所有子线程的结果，每次都是server receive时put操作，server send时remove操作，我再想下好的方案，或者大牛你有好的方案还请不吝赐教。

jvm参数加agent，业务方估计会比较排斥，因为不知道agent修改了哪些类，会担心影响性能和安全

**Comment by oldratlee** [comment]
关于『jvm参数加agent，业务方估计会比较排斥，因为不知道agent修改了哪些类，会担心影响性能和安全』：

- 关于『性能』，可以自己再测试一下。
- 关于『安全』，所有的代码是开源白盒的，确定实现机制和修改内容即可。

上面的事情是一次性的，比起业务不透明，让使用方代码保证，投入个人感觉是值得的。当然，前提是『你可以接管容器的运行方式』 :smile:

**Comment by wyzssw** [comment]
现在我们后端服务没有使用tomcat，只有api层使用了tomcat，后端各个服务都是一个单独的thrift-server，如果要添加agent需要事先将multithread.context-1.1.0-SNAPSHOT.jar部署到线上服务器上，或者放在工程lib目录里，对发布部署迁移升级带来些额外工作量。

**Comment by oldratlee** [comment]
> 你到提醒了我，我之前没有考虑oneway方法的rpc请求，只考虑了父线程会等到所有子线程的结果，每次都是server receive时put操作，server send时remove操作，我再想下好的方案，或者大牛你有好的方案还请不吝赐教。

我想到的解法是对『traceId』的Map做引用计数。

具体参见 [DistributedTracerUseDemo](https://github.com/alibaba/multi-thread-context/blob/distributed-tracer-support/src/test/java/com/alibaba/mtc/DistributedTracerUseDemo.java#L108)。


运行结果：

```bash
DEBUG: Increase reference counter(1) for traceId traceId-111 in thread main
DEBUG: Increase reference counter(2) for traceId traceId-111 in thread main
Do Rpc invocation to server server 2 with {traceId=traceId-111, spanId=baseSpanId-1.1.1}
Do Rpc invocation to server server 3 with {traceId=traceId-111, spanId=baseSpanId-1.1.3}
Do Rpc invocation to server server 1 with {traceId=traceId-111, spanId=baseSpanId-1.1.2}
DEBUG: Decrease reference counter(1) for traceId traceId-111 in thread Executors
DEBUG: Decrease reference counter(0) for traceId traceId-111 in thread main
DEBUG: Clear traceId2LeafSpanIdInfo for traceId traceId-111 in thread main
```

PS： 没有时间细说，看代码吧～

**Comment by oldratlee** [comment]
当然简单主的话，跨线程池时，让用户自己传递一下Context。

```java
final Object traceContext =  TraceContext.getTraceContext();

executor.submit(new Runnable() {
    public void run() {
        TraceContext.setTraceContext(traceContext);

        // biz code
    }
});
```

这样 让用户麻烦一些，但完全避开MTC及Context的持有和计数的问题。

**Comment by wyzssw** [comment]
太赞了，借助的MTC submit 的前置和后置方法 进行引用计数操作完美解决了这个问题。不过我使用的1.2.0版本没法成功执行 DistributedTracerUseDemo.java，子线程runnable对象退出未执行下列方法
 ``` java
      @Override
        protected void afterExecute() {
            decreaseSpanIdRefCounter();
        }
```
我clone了distributed-tracer-support分支是运行成功了，可否将新版本发布到maven仓库中？

我在`thrift-rpc`框架中添加了`tracerFilter`可以在client端或者service端执行`invokeBefore` 和`invokeBefore` 方法，添加增减计数操作，但是如果父线程执行比较快，还未来得及执行子线程，父线程退出，计数操作为0就清空了计数器，使用MTC在submit前执行计数加1，完美解决了这个问题。

我的`trace`框架只开放给使用方`TraceIdContext.getTraceId()`方法 ,让其可以将traceId打到他自定义的日志中，至于`span`等信息，我不希望用户关心，`dapper`论文中也强调分布式追踪要对应用透明

**Comment by oldratlee** [comment]
> 不过我使用的1.2.0版本没法成功执行 DistributedTracerUseDemo.java，子线程runnable对象退出未执行方法afterExecute  
> 我clone了distributed-tracer-support分支是运行成功了，可否将新版本发布到maven仓库中？

是的，distributed-tracer-support分支有修复这个问题的提交。尽量今天会合到`master`，并发布。

> trace框架只开放给使用方TraceIdContext.getTraceId()方法 ,让其可以将traceId打到他自定义的日志中，

『trace框架只开放给使用方TraceIdContext.getTraceId()方法』赞成！

推荐建议：

- `TraceIdContext.getTraceId()` 类名改成 `TraceContext.getTraceId()` ，概念范围上比较自然些，也方便把其它信息放到 `TraceContext`中。
- 如果让用户帮助触发做引用计数，方法名推荐『borrow/return』。这样可以体现要配套调用且不能多次调用 的契约。

> 至于span等信息，我不希望用户关心，dapper论文中也强调分布式追踪要对应用透明
:+1: 
`Dapper`之前了解过，论文还一直没有去读

**Comment by wyzssw** [comment]
:+1:  多谢大牛的指点，我会在代码里改正，又学到不少东西，之前你写的show-busy-java-threads.sh我一直在用 :smile:

**Comment by oldratlee** [comment]
Fix了 『没有 afterExecute 的回调 #54 』

[1.2.1 release](https://github.com/alibaba/multi-thread-context/releases/tag/v1.2.1)了，已经发到了Maven中央库了。

关于前面说的『引用计数』解法，在`Java`里因为有`GC`，复杂了，使用`WeakReference`来解更合适。

详见Demo [DistributedTracerUseDemo_WeakReferenceInsteadOfRefCounter.java](https://github.com/alibaba/multi-thread-context/blob/master/src/test/java/com/alibaba/mtc/demo/distributed_tracer/DistributedTracerUseDemo_WeakReferenceInsteadOfRefCounter.java)
\# 老Demo在
[DistributedTracerUseDemo.java](https://github.com/alibaba/multi-thread-context/blob/master/src/test/java/com/alibaba/mtc/demo/distributed_tracer/DistributedTracerUseDemo.java)

**Comment by wyzssw** [comment]
多谢发布，之前考虑过用guava weakvalue，但是无法达到需求，我看新demo也有这个问题 ，父线程退出，子线程还没来得及执行，会出现强引用退出，只剩下cache中弱引用触发remove。
我在127行和135行分别打了断点会出现LeafSpanIdInfo is NOT present, Bug情况
``` java
new Thread(new Runnable() {
            @Override
            public void run() {
                syncMethod_ByNewThread(); //断点处
            }
        }, "Thread-by-new").start();
```

**Comment by oldratlee** [comment]
> 我看新demo也有这个问题 ，父线程退出，子线程还没来得及执行，会出现强引用退出，只剩下cache中弱引用触发remove。

问题Fix了，见上面的提交。

MtContextThreadLocal 的持有是安全的，线程退出时，会被释放，不影响GC。

结果如下：

```bash
Do Rpc invocation to server server 3 with {traceId=traceId_XXXYYY38, spanId=1.1.3}
Do Rpc invocation to server server 2 with {traceId=traceId_XXXYYY39, spanId=1.1.1}
Do Rpc invocation to server server 3 with {traceId=traceId_XXXYYY39, spanId=1.1.3}
Do Rpc invocation to server server 1 with {traceId=traceId_XXXYYY39, spanId=1.1.2}
Finished Rpc call traceId_XXXYYY39 with span LeafSpanIdInfo{current=4}.
Do Rpc invocation to server server 2 with {traceId=traceId_XXXYYY40, spanId=1.1.1}
Do Rpc invocation to server server 3 with {traceId=traceId_XXXYYY40, spanId=1.1.3}
Do Rpc invocation to server server 1 with {traceId=traceId_XXXYYY40, spanId=1.1.2}
Finished Rpc call traceId_XXXYYY40 with span LeafSpanIdInfo{current=4}.
Do Rpc invocation to server server 2 with {traceId=traceId_XXXYYY41, spanId=1.1.1}
Do Rpc invocation to server server 3 with {traceId=traceId_XXXYYY41, spanId=1.1.3}
Do Rpc invocation to server server 1 with {traceId=traceId_XXXYYY41, spanId=1.1.2}
Finished Rpc call traceId_XXXYYY41 with span LeafSpanIdInfo{current=4}.
Do Rpc invocation to server server 2 with {traceId=traceId_XXXYYY42, spanId=1.1.1}
Do Rpc invocation to server server 1 with {traceId=traceId_XXXYYY42, spanId=1.1.2}
Finished Rpc call traceId_XXXYYY42 with span LeafSpanIdInfo{current=4}.
Do Rpc invocation to server server 3 with {traceId=traceId_XXXYYY42, spanId=1.1.3}
DEBUG: Remove traceId traceId_XXXYYY38 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY28 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY14 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY41 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY11 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY3 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY33 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY20 in thread main by cause COLLECTED: null
DEBUG: Remove traceId traceId_XXXYYY25 in thread main by cause COLLECTED: null
```

**Comment by oldratlee** [comment]
『让 MtContextThreadLocal 持有 LeafSpanIdInfo』的做法应该是 正解！

再看了一下代码，这样做了之后，不再需要`CacheBuilder`，实现 简单直接了不少！

详见 提交 798eff8e7cf80098db212f1498c3b8bbb3c86d64

**Comment by wyzssw** [comment]
经过你这么一说，我也明白了，MTC在传递给子线程时并不是深拷贝，用版本1.2.0也可以，只不过要改下类型
```java
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;

import com.alibaba.mtc.MtContextThreadLocal;
import com.alibaba.mtc.threadpool.MtContextExecutors;
import com.google.common.base.Optional;


public class Test {
  public static void main(String[] args) throws InterruptedException {
    ExecutorService service = Executors.newFixedThreadPool(10);
    ExecutorService executorService = MtContextExecutors.getMtcExecutorService(service);

    final MtContextThreadLocal<Optional<AtomicLong>> parent =
        new MtContextThreadLocal<Optional<AtomicLong>>();
    parent.set(Optional.of(new AtomicLong(0)));

    System.out.println("Parent-start at spanId " + parent.get().get().incrementAndGet());

    // 挤满线程
    for (int i = 0; i < 10; i++) {
      service.submit(new Runnable() {
        @Override
        public void run() {}
      });
    }

    // 提交任务，执行rpc调用
    for (int i = 0; i < 30; i++) {
      executorService.submit(new Runnable() {

        @Override
        public void run() {
          Optional<AtomicLong> spanIncr = parent.get();
          if (spanIncr.isPresent()) {
            // 打印输出子线程所需的spanId
            System.out.println("Sub start at spanId " + spanIncr.get().incrementAndGet());
          }
        }
      });
    }
    // 打印父线程退出的spanId
    System.out.println("Parent-end at spanId " + parent.get().get().incrementAndGet());
  }
}

```

输出
```
Parent-start at spanId 1
Sub start at spanId 4
Sub start at spanId 7
Sub start at spanId 10
Sub start at spanId 12
Sub start at spanId 8
Sub start at spanId 9
Sub start at spanId 17
Sub start at spanId 6
Sub start at spanId 19
Sub start at spanId 5
Sub start at spanId 21
Sub start at spanId 3
Sub start at spanId 23
Sub start at spanId 2
Sub start at spanId 25
Sub start at spanId 24
Sub start at spanId 27
Sub start at spanId 22
Sub start at spanId 29
Sub start at spanId 20
Sub start at spanId 18
Parent-end at spanId 16
Sub start at spanId 15
Sub start at spanId 14
Sub start at spanId 13
Sub start at spanId 11
Sub start at spanId 32
Sub start at spanId 31
Sub start at spanId 30
Sub start at spanId 28
Sub start at spanId 26
```
 『为了让性能测试 更容易发现问题，在测试时，让MtContextThreadLocal多持有一个测试用时Dummy大对象即可』,:+1: 新技能get√，多谢指点 :smile:

**Comment by oldratlee** [comment]
缺省是浅拷贝，可以通过覆盖`copy`方法自定义。这个行为 1.2.0 和 1.2.1 是一样的。1.2.1只修复了afterExecute回调有的bug。

整个过程应该无需Optional的。

**Comment by wyzssw** [comment]
嘿嘿，果然，去除Optional也行:+1:

**Comment by oldratlee** [comment]
多谢反馈，发现了bug，也一起深入梳理了 分布式追踪 场景mtc的使用方式。:+1:

close了

**Comment by wyzssw** [comment]
嗯，和牛人交流，收获很多，以后多多交流:clap:

**Comment by oldratlee** [comment]
通过`finalize`方法，重新输出`GC`操作日志。

可以确认到100%回收了`DtTransferInfo`对象。

**Comment by edwinmin** [comment]
你好，backupAndSet和restore里面对于holder的迭代操作细节有点不太清楚，能大概解释下主要是什么目的吗？

**Comment by zavakid** [comment]
:+1: cool

**Comment by duguyixiaono1** [comment]
学习

**Comment by blurooo** [comment]
看得我跳了起来

**Comment by wysstartgo** [comment]
学习了

**Comment by GuooH** [comment]
学习了

**Comment by huangbuhuan** [comment]
学习了

**Comment by yuanrengu** [comment]
学习了

**Comment by simplifyOurLife** [comment]
学习了

**Comment by zzq666666** [comment]
学习了，膜拜一下。对技术追求极致，才能不断进步。

**Comment by linglinghu5** [comment]
学习了

**Comment by ZeTao522** [comment]
cool

**Comment by springboot4** [comment]
good

**Comment by ling0900** [comment]
2024年了，不知道还有伙伴关注这块么，又学到了！

**Comment by ling0900** [comment]
> > 2024年了，不知道还有伙伴关注这块么，又学到了！
> 
> 可以有 💕😄 @ling0900

@oldratlee 大佬，我看您指点回复写的代码中，这里是不是应该做个小小修改🤔：testMethod.get()  ---->  storeTestContext.get()

**Comment by oldratlee** [comment]
> 这里是不是应该做个小小修改🤔：testMethod.get() ----> storeTestContext.get()

👍👌 已修改～
